- hosts: 172.31.3.4
  become: true
  tasks:
    - name: create new deployment 
      command: kubectl apply -f /home/ubuntu/deployment.yml
    - name: create a new service 
      command: kubectl apply -f /home/ubuntu/service.yml